#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm prettier --write '{controller,model,router}\**\*.ts'
# pnpm prettier --write 'model\**\*.ts'
# pnpm prettier --write 'router\**\*.ts'
git add .
